# Generated by Django 4.1.4 on 2023-03-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='hotel',
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.ManyToManyField(related_name='tours', to='turist.hotel'),
        ),
    ]
