# Generated by Django 4.1.4 on 2023-03-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0005_alter_hotel_image_alter_place_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='hotels'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='places'),
        ),
    ]
