# Generated by Django 4.1.4 on 2023-03-05 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0008_alter_tour_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turist.hotel'),
        ),
    ]
